import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { MatTooltipModule } from '@angular/material/tooltip';
import { TimeService } from '../../services/time.service';
import { Observable } from 'rxjs';
import { DailyActivity } from '../../models/DailyActivity';

export const Months = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const Weekdays = [
  'Sunday',
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
  'Saturday',
];

@Component({
  selector: 'time-heatmap',
  standalone: true,
  imports: [CommonModule, MatTooltipModule],
  templateUrl: './time-heatmap.component.html',
  styleUrl: './time-heatmap.component.scss',
})
export class TimeHeatmapComponent implements OnInit {
  MONTHS = Months;
  WEEKDAYS = Weekdays;

  year: Date[] = [];
  heightData = new Map<string, number>();

  constructor(private timeService: TimeService) {}

  ngOnInit(): void {
    let currentYear = new Date().getFullYear();
    this.year = [];
    this.year.push(...this.getAllDaysOfYear(currentYear));
    this.loadHeightData(currentYear);
  }

  /**
   * returns a list of all days within the current year
   * @returns
   */
  getAllDaysOfYear(year: number): Date[] {
    let allDays: Date[] = [];
    for (let i = 1; i < 13; i++) {
      let month = this.getAllDaysInMonth(i, year);

      allDays.push(...month);
    }

    return allDays;
  }

  /**
   * returns a list of all days in the month
   * @param month index of the month - starting with 1
   * @param year year as number
   * @returns
   */
  getAllDaysInMonth(month: number, year: number): Date[] {
    return Array.from(
      { length: new Date(year, month, 0).getDate() },
      (_, i) => new Date(year, month - 1, i + 1)
    );
  }

  /**
   * returns all days of the allDays array with the given weekday
   * @param weekday weekday (0-6) - monday => 1
   * @param allDays array of allDays that should be filtered
   * @returns
   */
  getAllDaysByDayOfWeek(weekday: number, allDays: Date[]): Date[] {
    let allWeekdays = allDays.filter((date) => {
      return date.getDay() == weekday;
    });

    if (weekday == 0) {
      if (allWeekdays[0].getDate() - 7 > 0) {
        allWeekdays.unshift(new Date(1970, 0, 1));
      }
    } else if (allWeekdays[0].getDate() - weekday > 0) {
      allWeekdays.unshift(new Date(1970, 0, 1));
    }

    return allWeekdays || [];
  }

  /**
   * returns a tooltip label generated by the day
   * @param day
   * @returns
   */
  getTooltip(day: Date): string {
    return day.getDate() + '.' + (day.getMonth() + 1);
  }

  /**
   * returns the data-level of the day
   * @param day
   * @returns
   */
  getDayLevel(day: Date): string {
    let time = this.heightData.get(day.toLocaleDateString());

    if (!time) return '0';
    if (time >= 1) return '4';
    if (time >= 0.75) return '3';
    if (time >= 0.5) return '2';
    if (time >= 0.25) return '1';

    return '0';
  }

  /**
   * load the height data for each day of the year
   * @param year
   */
  loadHeightData(year: number) {
    this.heightData.clear();

    this.timeService.getDailyActivity().subscribe((data) => {
      this.getAllDaysOfYear(year).forEach((day) => {
        let hasDataValues = data.filter((activity) => {
          if (!activity.day) return;
          return new Date(activity.day).toDateString() == day.toDateString();
        });

        this.heightData.set(
          day.toLocaleDateString(),
          hasDataValues[0]
            ? this.timeService.getHoursOfActivity(hasDataValues[0])
            : 0
        );
      });
    });
  }

  /**
   * get classname of the day element to seperate even and odd months
   * @param day
   * @returns
   */
  getClassname(day: Date): string {
    return day.getMonth() % 2 == 0 ? 'month-even' : 'month-odd';
  }

  /**
   * calculate the colspan width of the headers
   * @param month
   * @returns
   */
  getMonthColWidth(month: string): string {
    let firstRow = this.getAllDaysByDayOfWeek(1, this.year);
    let daysOfMonth = firstRow.filter((day) => {
      return day.getMonth() == this.MONTHS.indexOf(month);
    });

    return daysOfMonth.length.toString();
  }
}
